### ISSUE TITLE
Clean backups older than X days

### ISSUE THREAD

**Issue by tebjan** [sebescudie/GammaLauncher#35]
Autobackup creates a folder per day, one could get rid of them if older than 3 months or so, note that there are two folders, one for previews one for stables:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1094716/158801878-bd0801ca-9090-4d24-a4a3-5890b21f2b65.png">

**Comment by sebescudie** [comment]
Same reasoning as my comment in #34, this is totally doable but I have the feeling this feature belongs more to the editor than to the launcher. Because then, someone using the launcher would see a different behavior than someone not using it regarding something that's not directly related to the it. Does that make sense?

**Comment by tebjan** [comment]
the backup management could be in the settings, indeed. @iorec @untone-git what do you think?

**Comment by sebescudie** [comment]
Closing, created a forum thread [here](https://discourse.vvvv.org/t/ability-to-clear-backups-older-than-n-days/21200).
